### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Asveste** [ace10102/ArcaneFundamentals#2]

**Comment by SpoilersMC** [comment]
seems you found a solution to the config issue?
would you mind providing some context so i can see if theres a way i can prevent config loading issues for others?

**Comment by Asveste** [comment]
First of all, sorry for handling the issue the way I did... Later on I found out it isn't entirely an issue of Arcane Fundamentals so I wanted to delete the issue which wasn't possible so It came down to.. uhm.. this mess.

Some hours later we got a slightly different crashlog but this time it mentioned Mekanism Additions instead of Arcane Fundamentals.
The weird thing is, all of this happened after we already played for like 2 days. Out of nowhere the server refused to start.

Even now we still have not found a solution sadly. Generating a new world with new server files seems to do the trick but of course all of this could just happen again, leaving us with no solution again.
At the moment we're getting the server to start up fine but joining the world is not possible.

So yeah, thats the situation currently. Right now I'm making a post in the forge forum to see if someone else can help with this. I'm attaching the latest.log and debug.log on this comment too, maybe you know something, but I don't think Arcane Fundamentals is causing anything bad here.

[latest.log](https://github.com/ace10102/ArcaneFundamentals/files/7964991/latest.log)

[debug.log](https://github.com/ace10102/ArcaneFundamentals/files/7964990/debug.log)

**Comment by SpoilersMC** [comment]
no worries its probably the fault of the weird new forge config handler- something probably saved wrong or didnt save at all and broke the config files for your world- deleting and regenerating them/generating new ones in another world and moving them to your current world might solve your issues
